# Generated by Django 3.1.4 on 2020-12-21 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_bids_comments_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing-image'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(),
        ),
    ]
